name: latest

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '**/docker-image.yml'
      - 'check.sh'
      - 'default.conf'
      - 'entrypoint.sh'
      - 'healthcheck.sh'
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            coralhl/apt-mirror2:14
            coralhl/apt-mirror2:latest
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.CURRENT_DATE }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=apt-mirror2
            org.opencontainers.image.description=Docker implementation of apt-mirror2 with Nginx service added.
            org.opencontainers.image.licenses=GPL-3.0-or-later
            org.opencontainers.image.authors=coralhl
            org.opencontainers.image.source=https://github.com/coralhl/apt-mirror2-docker
            org.opencontainers.image.url=https://github.com/coralhl/apt-mirror2-docker
            org.opencontainers.image.version=14
          push: true
